### ISSUE TITLE
Parnell Kelley's portfolio page 

### ISSUE THREAD

**Issue by mrnelley** [ga-wdi-exercises/portfolio_pages#100]
http://github.com/mrnelley/mrnelley.github.io

comfortability: 3
completeness: 1

portfolio by no means complete, and i dont think ive ever felt this uncomfortable with git. it took me about 2.5 seconds to create the repo, clone and push updates to index.html and styles.css, BUT for some reason the file formatting that would render the page mrnelley.github.io just was.not.working. In the end I wrote whole new native files and then pushed them to a whole new repo. nothing like starting from scratch to teach you never to make a mistake again.

**Comment by superbuggy** [comment]
Starting from scratch is painful. The only thing that you need is an index.html and a repo named "username.github.io" where username is your user name, as far as I know. The design looks great though, great font choice and simple layout. Your code seems good so far. You might want to consider rotating it -30 degrees if you want the vertices to point up and down, but that's just a thought, since I am not sure what you want to do with it yet. I assume it's going to a frame an image. When we learn more js, you may give some thought to using that for the animation instead of CSS; but that really depends on what you are trying to do.

**Comment by superbuggy** [comment]
It looks like your design basically functions responsively, but you might want to think about mobile optimization in the future as well.
