### ISSUE TITLE
Aubrey Northam's Portfolio

### ISSUE THREAD

**Issue by aubreynortham** [ga-wdi-exercises/portfolio_pages#110]
https://github.com/aubreynortham/aubreynortham.github.io.git

Completeness: 4.5
Comfort: 4

I feel good about completing all the basic elements I set out to layout for this "prototype" and there were definitely some good breakthrough moments on css positioning (that I thought I had a better understanding of before actually diving in) so I'd say comfort level of 4 is about right. I definitely want to get more advanced with some little details as I learn more, but I'm going for an overall really simple and minimalist look, so I'm happy with this progress.

**Comment by superbuggy** [comment]
This looks absolutely fantastic! I'm just gonna go into suggestions since I feel like this is a super effective layout that communicates your aesthetic preferences without you saying a word. 

For mobile, you might want to look at ways to force the navbar to sit at the bottom. You can preview mobile mode in the browser's inspector (highlighted in blue): 
![image](https://cloud.githubusercontent.com/assets/17716232/16587348/41fb30e8-4298-11e6-9cca-98cbbb82a71d.png)

You might incorporate that vertical, dividing line you wanted to have in your HTML & CSS in your logo .png; that could be the simpler approach.
