### ISSUE TITLE
Chris Phillips Portfolio Page

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/portfolio_pages#118]
https://github.com/gsuskrice/gsuskrice.github.io

Comfort level: 2.0
Completeness: 2.0

Not even close to being done with this yet 

Short list of things I've written down to get to on this - probably will get longer every day honestly

Jekyll Project-Todo
    -find a more elegant JS method for implementation-
    -About me page Resume format and content
    -Project Page Summary format and content
    -format Blog
    -media query responsive implementation (looking to design mixin's for this with sass)
    -Bar links/nav bar/screen sizes etc)

This was the JS I was trying to implement - could not find a way I wanted to implement 

```
function check_input() {
    if(input == secret) {
        document.getElementById('mario').style.backgroundImage = "url('mario.png')";
    }
}
var secret = "38384040373937396665",
input = "",
timer;

document.onkeydown = function(e){
    input += e.which;
    clearTimeout(timer);
    timer = setTimeout(function() { input = ""; }, 1000);
    check_input();
}

```

**Comment by nayana487** [comment]
Hey, 

Since it looks like you're trying to implement a back end, I'm not able to view this page with just the html and css provided. Regarding the JS code you provided, the main thing is there isn't an element with the id "mario" or an image file provided, so the check_input function will never do anything. It looks like you were trying to record key presses on the page and display the image if the key press sequence matched the pattern you stored in var secret. It's not common to track key presses over an entire document, it may cleaner to add an input element in the html and compare strings instead of codes. The code works if you just put in an alert in the check_input function on a match, which is a good way to start off if you're having trouble with DOM manipulation.

**Comment by ghost** [comment]
Thanks! 

Would it be possible to go over this this week in person? I want to see if I'm on the right track as far as design goes for this project. There are probably a TON of issues I'm going to run into as this get's bigger that I could probably head off now if I refactored some of the code.

Thanks again Nayana!

**Comment by ghost** [comment]
Also because I changed my user-name just now the new page is listed here:
chris-A-phillips.github.io

repo link is here: https://github.com/chris-A-phillips/chris-A-phillips.github.io
