### ISSUE TITLE
sanjay persaud (Portfolio Pages)

### ISSUE THREAD

**Issue by sanjaywallah** [ga-wdi-exercises/portfolio_pages#262]
sanjaywallah.github.io

**Comment by sanjaywallah** [comment]
sanjaywallah.github.io

**Comment by jsm13** [comment]
Be sure to include scores for **comfort/confidence** and **completion** on all submissions (and optionally any questions you have that I can help with).

Looks good!

Also, note that if you make a PR without a message, you can edit it by clicking the pencil icon in the top corner (I went ahead and moved the content of your second message into the original one because I have weird idiosyncrasies)
